# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-25 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('swimming', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('hiking', models.CharField(max_length=300)),
                ('dining', models.CharField(max_length=300)),
                ('luxery', models.CharField(max_length=300)),
                ('shopping', models.CharField(max_length=300)),
                ('fishing', models.CharField(max_length=300)),
                ('surfing', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
