# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-26 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradise_tailored_app', '0002_auto_20190926_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text_swim',
            new_name='choice_text',
        ),
    ]
