# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-26 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradise_tailored_app', '0003_auto_20190926_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='luxery',
            new_name='luxury',
        ),
    ]
