# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-27 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradise_tailored_app', '0005_auto_20190926_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='catagory',
            new_name='category',
        ),
    ]
